const fetch = require('node-fetch');

exports.getCovid19 = async (req, res) => {
    res.set('Access-Control-Allow-Origin', "*");
    res.set('Access-Control-Allow-Methods', 'GET');
    const response = await fetch(`https://disease.sh/v3/covid-19/historical/Afghanistan,Albania,Algeria,Andorra,Angola,Antigua%20and%20Barbuda,Argentina,Armenia,Australia,Austria,Azerbaijan,Bahamas,Bahrain,Bangladesh,Barbados,Belarus,Belgium,Belize,Benin,Bhutan,Bolivia,Bosnia,Botswana,Brazil,Brunei,Bulgaria,Burkina%20Faso,Burma,Burundi,Cabo%20Verde,Cambodia,Cameroon,Canada,Central%20African%20Republic,Chad,Chile,China,Colombia,Comoros,Congo,DRC,Costa%20Rica,C%C3%B4te%20d'Ivoire,Croatia,Cuba,Cyprus,Czechia,Denmark,Djibouti,Dominica,Dominican%20Republic,Ecuador,Egypt,El%20Salvador,Equatorial%20Guinea,Eritrea,Estonia,Swaziland,Ethiopia,Fiji,Finland,France,Gabon,Gambia,Georgia,Germany,Ghana,Greece,Grenada,Guatemala,Guinea,Guinea-Bissau,Guyana,Haiti,Holy%20See,Honduras,Hungary,Iceland,India,Indonesia,Iran,Iraq,Ireland,Israel,Italy,Jamaica,Japan,Jordan,Kazakhstan,Kenya,S.%20Korea,Kosovo,Kuwait,Kyrgyzstan,Lao%20People's%20Democratic%20Republic,Latvia,Lebanon,Lesotho,Liberia,Libyan%20Arab%20Jamahiriya,Liechtenstein,Lithuania,Luxembourg,Madagascar,Malawi,Malaysia,Maldives,Mali,Malta,Marshall%20Islands,Mauritania,Mauritius,Mexico,Micronesia,Moldova,Monaco,Mongolia,Montenegro,Morocco,Mozambique,Namibia,Nepal,Netherlands,New%20Zealand,Nicaragua,Niger,Nigeria,Macedonia,Norway,Oman,Pakistan,Panama,Papua%20New%20Guinea,Paraguay,Peru,Philippines,Poland,Portugal,Qatar,Romania,Russia,Rwanda,Saint%20Kitts%20and%20Nevis,Saint%20Lucia,Saint%20Vincent%20and%20the%20Grenadines,Samoa,San%20Marino,Sao%20Tome%20and%20Principe,Saudi%20Arabia,Senegal,Serbia,Seychelles,Sierra%20Leone,Singapore,Slovakia,Slovenia,Solomon%20Islands,Somalia,South%20Africa,South%20Sudan,Spain,Sri%20Lanka,Sudan,Suriname,Sweden,Switzerland,Syrian%20Arab%20Republic,Taiwan,Tajikistan,Tanzania,Thailand,Timor-Leste,Togo,Trinidad%20and%20Tobago,Tunisia,Turkey,USA,Uganda,Ukraine,UAE,UK,Uruguay,Uzbekistan,Vanuatu,Venezuela,Vietnam,West%20Bank%20and%20Gaza,Yemen,Zambia,Zimbabwe?lastdays=all`);
    const data = await response.json();
    res.status(200).send(data);
};
